name: ScreenPets
options:
  bundleIdPrefix: com.sealovesky
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  ScreenPets:
    type: application
    platform: macOS
    sources:
      - path: ScreenPets
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sealovesky.ScreenPets
        INFOPLIST_FILE: ScreenPets/Info.plist
        CODE_SIGN_ENTITLEMENTS: ScreenPets/ScreenPets.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
    info:
      path: ScreenPets/Info.plist
      properties:
        LSUIElement: true
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSHumanReadableCopyright: "Copyright © 2024. All rights reserved."
